[package]
name = "ProcNascMorte"
version = "0.1.0"
authors = ["Marcelo Heredia <marcelo.heredia@acad.pucrs.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "ProcNascMorte"
path = "main.rs"
